In [1]:
class Employee:

    # Creating a data member to count the number of Employees

    no_of_employees = 0
    # Initializing name, family, salary, department

    def __init__(self, name, family_name, salary, department):
        self.__name = name
        self.__family_name = family_name
        self.salary = salary
        self.__department = department
        Employee.no_of_employees += 1
     #Creating a function to average salary
    @staticmethod
    def average_salary(employees):

        sum = 0
        for employee in employees:
            sum += employee.salary
        return sum / Employee.no_of_employees
      #Creating a Fulltime Employee class
class FulltimeEmployee(Employee):

    def __init__(self, name, family_name, salary, department):
        super().__init__(name, family_name, salary, department)

    def full_time_benefits(self):
        print("Few benefits as full time employee.")

# Creating the instances of Fulltime Employee class and Employee class and also calling their member functions.

def main():
    employees = []
    fte1 = FulltimeEmployee("Employee1", "FamilyName1", 120000, "Management")
    fte1.full_time_benefits()
    employees.append(fte1)
    fte2 = FulltimeEmployee("Employee2", "FamilyName2", 180000, "RnD")
    employees.append(fte2)
    emp1 = Employee("Employee3", "FamilyName3", 160000, "Marketing")
    employees.append(emp1)
    emp2 = Employee("Employee4", "FamilyName4", 135000, "HR")
    employees.append(emp2)
    print("Average salary:", FulltimeEmployee.average_salary(employees))


if __name__ == "__main__":
    main()


Few benefits as full time employee.
Average salary: 148750.0


In [2]:
import numpy as np

                                   #Creating a random vector of size 20
v = np.random.uniform(1, 20, 20)

v = v. reshape(4, 5)  # Reshape the array to 4 by 5

print(v)

v[np.arange(4), v.argmax(axis=1)]=0 # Replace the max value with 0 (axis=1)
print(v)


[[19.57689122  5.62735693 18.52216278 11.45594417  4.14317251]
 [ 8.35175576  2.76617517  8.44664661 16.13327749  5.53420942]
 [ 1.49039876  6.27035742  7.86094095 11.14952153 17.50804802]
 [ 9.98404881 13.71169958  1.43851638 16.47247609  4.45428565]]
[[ 0.          5.62735693 18.52216278 11.45594417  4.14317251]
 [ 8.35175576  2.76617517  8.44664661  0.          5.53420942]
 [ 1.49039876  6.27035742  7.86094095 11.14952153  0.        ]
 [ 9.98404881 13.71169958  1.43851638  0.          4.45428565]]
